name: CI
on:
  - push
  - pull_request

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - jruby-9.4.1.0
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"

    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup project
        run: bundle install
      - name: Run test
        run: bundle exec rake
